spring:
  application:
    name:
      Journal App
  data:
    mongodb: //add your userid & paasowrd
    database: journaldb
    auto-index-creation: true
server:
  port: 8080
  servlet:
    context-path: /journal

